export type Element = {
  Z: number
  symbol: string
  name: { en: string; fr: string; ar: string }
}

// Z=1..92 (Hydrogen through Uranium). Names in en/fr/ar.
export const ELEMENTS: Element[] = [
  { Z: 1,  symbol: 'H',  name: { en: 'Hydrogen',     fr: 'Hydrogène',   ar: 'هيدروجين'  } },
  { Z: 2,  symbol: 'He', name: { en: 'Helium',       fr: 'Hélium',      ar: 'هيليوم'    } },
  { Z: 3,  symbol: 'Li', name: { en: 'Lithium',      fr: 'Lithium',     ar: 'ليثيوم'    } },
  { Z: 4,  symbol: 'Be', name: { en: 'Beryllium',    fr: 'Béryllium',   ar: 'بيريليوم'  } },
  { Z: 5,  symbol: 'B',  name: { en: 'Boron',        fr: 'Bore',        ar: 'بورون'     } },
  { Z: 6,  symbol: 'C',  name: { en: 'Carbon',       fr: 'Carbone',     ar: 'كربون'     } },
  { Z: 7,  symbol: 'N',  name: { en: 'Nitrogen',     fr: 'Azote',       ar: 'نيتروجين'  } },
  { Z: 8,  symbol: 'O',  name: { en: 'Oxygen',       fr: 'Oxygène',     ar: 'أكسجين'    } },
  { Z: 9,  symbol: 'F',  name: { en: 'Fluorine',     fr: 'Fluor',       ar: 'فلور'      } },
  { Z: 10, symbol: 'Ne', name: { en: 'Neon',         fr: 'Néon',        ar: 'نيون'      } },
  { Z: 11, symbol: 'Na', name: { en: 'Sodium',       fr: 'Sodium',      ar: 'صوديوم'    } },
  { Z: 12, symbol: 'Mg', name: { en: 'Magnesium',    fr: 'Magnésium',   ar: 'مغنيسيوم'  } },
  { Z: 13, symbol: 'Al', name: { en: 'Aluminium',    fr: 'Aluminium',   ar: 'ألمنيوم'   } },
  { Z: 14, symbol: 'Si', name: { en: 'Silicon',      fr: 'Silicium',    ar: 'سيليكون'   } },
  { Z: 15, symbol: 'P',  name: { en: 'Phosphorus',   fr: 'Phosphore',   ar: 'فسفور'     } },
  { Z: 16, symbol: 'S',  name: { en: 'Sulfur',       fr: 'Soufre',      ar: 'كبريت'     } },
  { Z: 17, symbol: 'Cl', name: { en: 'Chlorine',     fr: 'Chlore',      ar: 'كلور'      } },
  { Z: 18, symbol: 'Ar', name: { en: 'Argon',        fr: 'Argon',       ar: 'أرغون'     } },
  { Z: 19, symbol: 'K',  name: { en: 'Potassium',    fr: 'Potassium',   ar: 'بوتاسيوم'  } },
  { Z: 20, symbol: 'Ca', name: { en: 'Calcium',      fr: 'Calcium',     ar: 'كالسيوم'   } },
  { Z: 21, symbol: 'Sc', name: { en: 'Scandium',     fr: 'Scandium',    ar: 'سكانديوم'  } },
  { Z: 22, symbol: 'Ti', name: { en: 'Titanium',     fr: 'Titane',      ar: 'تيتانيوم'  } },
  { Z: 23, symbol: 'V',  name: { en: 'Vanadium',     fr: 'Vanadium',    ar: 'فاناديوم'  } },
  { Z: 24, symbol: 'Cr', name: { en: 'Chromium',     fr: 'Chrome',      ar: 'كروم'      } },
  { Z: 25, symbol: 'Mn', name: { en: 'Manganese',    fr: 'Manganèse',   ar: 'منغنيز'    } },
  { Z: 26, symbol: 'Fe', name: { en: 'Iron',         fr: 'Fer',         ar: 'حديد'      } },
  { Z: 27, symbol: 'Co', name: { en: 'Cobalt',       fr: 'Cobalt',      ar: 'كوبالت'    } },
  { Z: 28, symbol: 'Ni', name: { en: 'Nickel',       fr: 'Nickel',      ar: 'نيكل'      } },
  { Z: 29, symbol: 'Cu', name: { en: 'Copper',       fr: 'Cuivre',      ar: 'نحاس'      } },
  { Z: 30, symbol: 'Zn', name: { en: 'Zinc',         fr: 'Zinc',        ar: 'زنك'       } },
  { Z: 31, symbol: 'Ga', name: { en: 'Gallium',      fr: 'Gallium',     ar: 'غاليوم'    } },
  { Z: 32, symbol: 'Ge', name: { en: 'Germanium',    fr: 'Germanium',   ar: 'جرمانيوم'  } },
  { Z: 33, symbol: 'As', name: { en: 'Arsenic',      fr: 'Arsenic',     ar: 'زرنيخ'     } },
  { Z: 34, symbol: 'Se', name: { en: 'Selenium',     fr: 'Sélénium',    ar: 'سيلينيوم'  } },
  { Z: 35, symbol: 'Br', name: { en: 'Bromine',      fr: 'Brome',       ar: 'بروم'      } },
  { Z: 36, symbol: 'Kr', name: { en: 'Krypton',      fr: 'Krypton',     ar: 'كريبتون'   } },
  { Z: 37, symbol: 'Rb', name: { en: 'Rubidium',     fr: 'Rubidium',    ar: 'روبيديوم'  } },
  { Z: 38, symbol: 'Sr', name: { en: 'Strontium',    fr: 'Strontium',   ar: 'سترونشيوم' } },
  { Z: 39, symbol: 'Y',  name: { en: 'Yttrium',      fr: 'Yttrium',     ar: 'إتريوم'    } },
  { Z: 40, symbol: 'Zr', name: { en: 'Zirconium',    fr: 'Zirconium',   ar: 'زركونيوم'  } },
  { Z: 41, symbol: 'Nb', name: { en: 'Niobium',      fr: 'Niobium',     ar: 'نيوبيوم'   } },
  { Z: 42, symbol: 'Mo', name: { en: 'Molybdenum',   fr: 'Molybdène',   ar: 'موليبدنوم' } },
  { Z: 43, symbol: 'Tc', name: { en: 'Technetium',   fr: 'Technétium',  ar: 'تكنيشيوم'  } },
  { Z: 44, symbol: 'Ru', name: { en: 'Ruthenium',    fr: 'Ruthénium',   ar: 'روثينيوم'  } },
  { Z: 45, symbol: 'Rh', name: { en: 'Rhodium',      fr: 'Rhodium',     ar: 'روديوم'    } },
  { Z: 46, symbol: 'Pd', name: { en: 'Palladium',    fr: 'Palladium',   ar: 'بلاديوم'   } },
  { Z: 47, symbol: 'Ag', name: { en: 'Silver',       fr: 'Argent',      ar: 'فضة'       } },
  { Z: 48, symbol: 'Cd', name: { en: 'Cadmium',      fr: 'Cadmium',     ar: 'كادميوم'   } },
  { Z: 49, symbol: 'In', name: { en: 'Indium',       fr: 'Indium',      ar: 'إنديوم'    } },
  { Z: 50, symbol: 'Sn', name: { en: 'Tin',          fr: 'Étain',       ar: 'قصدير'     } },
  { Z: 51, symbol: 'Sb', name: { en: 'Antimony',     fr: 'Antimoine',   ar: 'أنتيمون'   } },
  { Z: 52, symbol: 'Te', name: { en: 'Tellurium',    fr: 'Tellure',     ar: 'تيلوريوم'  } },
  { Z: 53, symbol: 'I',  name: { en: 'Iodine',       fr: 'Iode',        ar: 'يود'       } },
  { Z: 54, symbol: 'Xe', name: { en: 'Xenon',        fr: 'Xénon',       ar: 'زينون'     } },
  { Z: 55, symbol: 'Cs', name: { en: 'Cesium',       fr: 'Césium',      ar: 'سيزيوم'    } },
  { Z: 56, symbol: 'Ba', name: { en: 'Barium',       fr: 'Baryum',      ar: 'باريوم'    } },
  { Z: 57, symbol: 'La', name: { en: 'Lanthanum',    fr: 'Lanthane',    ar: 'لانثانوم'  } },
  { Z: 58, symbol: 'Ce', name: { en: 'Cerium',       fr: 'Cérium',      ar: 'سيريوم'    } },
  { Z: 59, symbol: 'Pr', name: { en: 'Praseodymium', fr: 'Praséodyme',  ar: 'براسيوديميوم' } },
  { Z: 60, symbol: 'Nd', name: { en: 'Neodymium',    fr: 'Néodyme',     ar: 'نيوديميوم' } },
  { Z: 61, symbol: 'Pm', name: { en: 'Promethium',   fr: 'Prométhium',  ar: 'بروميثيوم' } },
  { Z: 62, symbol: 'Sm', name: { en: 'Samarium',     fr: 'Samarium',    ar: 'ساماريوم'  } },
  { Z: 63, symbol: 'Eu', name: { en: 'Europium',     fr: 'Europium',    ar: 'يوروبيوم'  } },
  { Z: 64, symbol: 'Gd', name: { en: 'Gadolinium',   fr: 'Gadolinium',  ar: 'جادولينيوم' } },
  { Z: 65, symbol: 'Tb', name: { en: 'Terbium',      fr: 'Terbium',     ar: 'تربيوم'    } },
  { Z: 66, symbol: 'Dy', name: { en: 'Dysprosium',   fr: 'Dysprosium',  ar: 'ديسبروسيوم' } },
  { Z: 67, symbol: 'Ho', name: { en: 'Holmium',      fr: 'Holmium',     ar: 'هولميوم'   } },
  { Z: 68, symbol: 'Er', name: { en: 'Erbium',       fr: 'Erbium',      ar: 'إربيوم'    } },
  { Z: 69, symbol: 'Tm', name: { en: 'Thulium',      fr: 'Thulium',     ar: 'ثوليوم'    } },
  { Z: 70, symbol: 'Yb', name: { en: 'Ytterbium',    fr: 'Ytterbium',   ar: 'إتربيوم'   } },
  { Z: 71, symbol: 'Lu', name: { en: 'Lutetium',     fr: 'Lutécium',    ar: 'لوتيتيوم'  } },
  { Z: 72, symbol: 'Hf', name: { en: 'Hafnium',      fr: 'Hafnium',     ar: 'هافنيوم'   } },
  { Z: 73, symbol: 'Ta', name: { en: 'Tantalum',     fr: 'Tantale',     ar: 'تنتالوم'   } },
  { Z: 74, symbol: 'W',  name: { en: 'Tungsten',     fr: 'Tungstène',   ar: 'تنغستن'    } },
  { Z: 75, symbol: 'Re', name: { en: 'Rhenium',      fr: 'Rhénium',     ar: 'رينيوم'    } },
  { Z: 76, symbol: 'Os', name: { en: 'Osmium',       fr: 'Osmium',      ar: 'أوسميوم'   } },
  { Z: 77, symbol: 'Ir', name: { en: 'Iridium',      fr: 'Iridium',     ar: 'إريديوم'   } },
  { Z: 78, symbol: 'Pt', name: { en: 'Platinum',     fr: 'Platine',     ar: 'بلاتين'    } },
  { Z: 79, symbol: 'Au', name: { en: 'Gold',         fr: 'Or',          ar: 'ذهب'       } },
  { Z: 80, symbol: 'Hg', name: { en: 'Mercury',      fr: 'Mercure',     ar: 'زئبق'      } },
  { Z: 81, symbol: 'Tl', name: { en: 'Thallium',     fr: 'Thallium',    ar: 'ثاليوم'    } },
  { Z: 82, symbol: 'Pb', name: { en: 'Lead',         fr: 'Plomb',       ar: 'رصاص'      } },
  { Z: 83, symbol: 'Bi', name: { en: 'Bismuth',      fr: 'Bismuth',     ar: 'بزموت'     } },
  { Z: 84, symbol: 'Po', name: { en: 'Polonium',     fr: 'Polonium',    ar: 'بولونيوم'  } },
  { Z: 85, symbol: 'At', name: { en: 'Astatine',     fr: 'Astate',      ar: 'أستاتين'   } },
  { Z: 86, symbol: 'Rn', name: { en: 'Radon',        fr: 'Radon',       ar: 'رادون'     } },
  { Z: 87, symbol: 'Fr', name: { en: 'Francium',     fr: 'Francium',    ar: 'فرانسيوم'  } },
  { Z: 88, symbol: 'Ra', name: { en: 'Radium',       fr: 'Radium',      ar: 'راديوم'    } },
  { Z: 89, symbol: 'Ac', name: { en: 'Actinium',     fr: 'Actinium',    ar: 'أكتينيوم'  } },
  { Z: 90, symbol: 'Th', name: { en: 'Thorium',      fr: 'Thorium',     ar: 'ثوريوم'    } },
  { Z: 91, symbol: 'Pa', name: { en: 'Protactinium', fr: 'Protactinium', ar: 'بروتكتينيوم' } },
  { Z: 92, symbol: 'U',  name: { en: 'Uranium',      fr: 'Uranium',     ar: 'يورانيوم'  } },
  { Z: 93, symbol: 'Np', name: { en: 'Neptunium',    fr: 'Neptunium',   ar: 'نبتونيوم'  } },
  { Z: 94, symbol: 'Pu', name: { en: 'Plutonium',    fr: 'Plutonium',   ar: 'بلوتونيوم' } },
]

const byZ = new Map<number, Element>(ELEMENTS.map((e) => [e.Z, e]))

export function elementFor(Z: number): Element | undefined {
  return byZ.get(Z)
}
